prometheus:
  thanos:
    create: true
    objectStorageConfig: 
      secretName: thanos-objstore-config
      secretKey: objstore.yml
    service: 
      type: LoadBalancer
  disableCompaction: true
  retention: 12h