existingObjstoreSecret: thanos-objstore-config
query:
  # dnsDiscovery:
  #   sidecarsService: kube-prometheus-prometheus-thanos
  #   sidecarsNamespace: monitoring
  stores:
    - kube-prometheus-prometheus-thanos.monitoring:10901
bucketweb:
  enabled: true
compactor:
  enabled: true
storegateway:
  enabled: true
ruler:
  enabled: true
  alertmanagers:
    - http://kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/kube-prometheus"})
metrics:
  enabled: true
  serviceMonitor:
    enabled: true