# existingObjstoreSecret: thanos-objstore-config
objstoreConfig: |-
  type: s3
  config:
    bucket: thanos
    endpoint: {{ include "thanos.minio.fullname" . }}.monitoring.svc.cluster.local:9000
    access_key: admin
    secret_key: minio123
    insecure: true
query:
  # dnsDiscovery:
  #   sidecarsService: kube-prometheus-prometheus-thanos
  #   sidecarsNamespace: monitoring
  stores:
    - thanos-storegateway.monitoring:9090
    - prometheus-kube-prometheus-prometheus-thanos.monitoring:10901
bucketweb:
  enabled: true
compactor:
  enabled: true
storegateway:
  enabled: true
ruler:
  enabled: true
  alertmanagers:
    - http://kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/kube-prometheus"})
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
minio:
  enabled: true
  auth:
    rootUser: "admin"
    rootPassword: "minio123"
  defaultBuckets: "thanos"
  accessKey:
    password: minio
  secretKey:
    password: minio123