dashboardsProvider:
  enabled: true
datasources:
  secretName: datasource-secret
dashboardsConfigMaps:
  - configMapName: node-exporter-full
    folderName: kubernetes
    fileName: node-exporter-full.json